-- CreateEnum
CREATE TYPE "CatalogStatus" AS ENUM ('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED', 'SCHEDULED', 'UNPUBLISHED');

-- CreateEnum
CREATE TYPE "ContentType" AS ENUM ('MOVIE', 'SERIES', 'EPISODE', 'SHORT', 'TRAILER', 'BONUS');

-- CreateEnum
CREATE TYPE "PricingModel" AS ENUM ('PPV', 'RENTAL', 'SUBSCRIPTION', 'HYBRID', 'FREE');

-- CreateEnum
CREATE TYPE "AccessWindowType" AS ENUM ('NONE', 'RENTAL_24H', 'RENTAL_48H', 'RENTAL_72H', 'LIFETIME', 'CUSTOM');

-- CreateEnum
CREATE TYPE "GeoRestrictionMode" AS ENUM ('ALLOWLIST', 'BLOCKLIST', 'NONE');

-- CreateEnum
CREATE TYPE "Visibility" AS ENUM ('PUBLIC', 'UNLISTED', 'PRIVATE');

-- CreateEnum
CREATE TYPE "MediaLanguageKind" AS ENUM ('AUDIO', 'SUBTITLE', 'DUB');

-- CreateTable
CREATE TABLE "tenants" (
    "id" TEXT NOT NULL,

    CONSTRAINT "tenants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "films" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "subtitle" TEXT,
    "description" TEXT,
    "synopsis" TEXT,
    "tagline" TEXT,
    "contentType" "ContentType" NOT NULL DEFAULT 'MOVIE',
    "status" "CatalogStatus" NOT NULL DEFAULT 'DRAFT',
    "visibility" "Visibility" NOT NULL DEFAULT 'PUBLIC',
    "pricingModel" "PricingModel" NOT NULL DEFAULT 'PPV',
    "accessWindow" "AccessWindowType" NOT NULL DEFAULT 'NONE',
    "runtimeSeconds" INTEGER,
    "releaseDate" TIMESTAMP(3),
    "publishAt" TIMESTAMP(3),
    "unpublishAt" TIMESTAMP(3),
    "ageRating" TEXT,
    "maturityRating" TEXT,
    "languageCode" TEXT,
    "countryOfOrigin" TEXT,
    "isFeatured" BOOLEAN NOT NULL DEFAULT false,
    "isOriginal" BOOLEAN NOT NULL DEFAULT false,
    "posterUrl" TEXT,
    "backdropUrl" TEXT,
    "trailerUrl" TEXT,
    "thumbnailUrl" TEXT,
    "searchKeywords" TEXT[],
    "cast" JSONB NOT NULL DEFAULT '[]',
    "crew" JSONB NOT NULL DEFAULT '[]',
    "genres" TEXT[],
    "tags" TEXT[],
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "seo" JSONB NOT NULL DEFAULT '{}',
    "geoRestrictionMode" "GeoRestrictionMode" NOT NULL DEFAULT 'NONE',
    "allowedCountries" TEXT[],
    "blockedCountries" TEXT[],
    "drmRequired" BOOLEAN NOT NULL DEFAULT false,
    "watermarkRequired" BOOLEAN NOT NULL DEFAULT false,
    "createdById" TEXT,
    "updatedById" TEXT,
    "publishedById" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "publishedAt" TIMESTAMP(3),
    "archivedAt" TIMESTAMP(3),

    CONSTRAINT "films_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "film_pricing" (
    "id" TEXT NOT NULL,
    "filmId" TEXT NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "ppvPrice" DECIMAL(10,2),
    "rentalPrice" DECIMAL(10,2),
    "subscriptionPrice" DECIMAL(10,2),
    "salePrice" DECIMAL(10,2),
    "compareAtPrice" DECIMAL(10,2),
    "rentalDurationHours" INTEGER,
    "subscriptionIncluded" BOOLEAN NOT NULL DEFAULT false,
    "bundleEligible" BOOLEAN NOT NULL DEFAULT true,
    "taxInclusive" BOOLEAN NOT NULL DEFAULT false,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "film_pricing_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "film_availability" (
    "id" TEXT NOT NULL,
    "filmId" TEXT NOT NULL,
    "startsAt" TIMESTAMP(3),
    "endsAt" TIMESTAMP(3),
    "preorderStartsAt" TIMESTAMP(3),
    "preorderEndsAt" TIMESTAMP(3),
    "isAvailable" BOOLEAN NOT NULL DEFAULT true,
    "regionLocked" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "film_availability_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "film_assets" (
    "id" TEXT NOT NULL,
    "filmId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "storageKey" TEXT NOT NULL,
    "url" TEXT,
    "mimeType" TEXT,
    "sizeBytes" BIGINT,
    "checksum" TEXT,
    "width" INTEGER,
    "height" INTEGER,
    "durationSeconds" INTEGER,
    "bitrateKbps" INTEGER,
    "isPrimary" BOOLEAN NOT NULL DEFAULT false,
    "isPublic" BOOLEAN NOT NULL DEFAULT false,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "film_assets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "film_subtitles" (
    "id" TEXT NOT NULL,
    "filmId" TEXT NOT NULL,
    "languageCode" TEXT NOT NULL,
    "kind" "MediaLanguageKind" NOT NULL DEFAULT 'SUBTITLE',
    "label" TEXT,
    "storageKey" TEXT NOT NULL,
    "url" TEXT,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "isForced" BOOLEAN NOT NULL DEFAULT false,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "film_subtitles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "film_chapters" (
    "id" TEXT NOT NULL,
    "filmId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "slug" TEXT,
    "startSeconds" INTEGER NOT NULL,
    "endSeconds" INTEGER,
    "orderIndex" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "film_chapters_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "film_variants" (
    "id" TEXT NOT NULL,
    "filmId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "qualityLabel" TEXT NOT NULL,
    "codec" TEXT,
    "container" TEXT,
    "storageKey" TEXT NOT NULL,
    "manifestUrl" TEXT,
    "bitrateKbps" INTEGER,
    "width" INTEGER,
    "height" INTEGER,
    "fps" DOUBLE PRECISION,
    "durationSeconds" INTEGER,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "isReady" BOOLEAN NOT NULL DEFAULT false,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "film_variants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "genres" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "description" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "genres_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "film_genres" (
    "filmId" TEXT NOT NULL,
    "genreId" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "film_genres_pkey" PRIMARY KEY ("filmId","genreId")
);

-- CreateTable
CREATE TABLE "bundles" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "price" DECIMAL(10,2),
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "bundles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "film_bundle_items" (
    "id" TEXT NOT NULL,
    "bundleId" TEXT NOT NULL,
    "filmId" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "film_bundle_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "watchlist_items" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "viewerUserId" TEXT NOT NULL,
    "filmId" TEXT NOT NULL,
    "notes" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "watchlist_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "film_ratings" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "viewerUserId" TEXT NOT NULL,
    "filmId" TEXT NOT NULL,
    "rating" INTEGER NOT NULL,
    "reviewTitle" TEXT,
    "reviewBody" TEXT,
    "isPublished" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "film_ratings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "films_tenantId_status_idx" ON "films"("tenantId", "status");

-- CreateIndex
CREATE INDEX "films_tenantId_visibility_idx" ON "films"("tenantId", "visibility");

-- CreateIndex
CREATE INDEX "films_tenantId_pricingModel_idx" ON "films"("tenantId", "pricingModel");

-- CreateIndex
CREATE INDEX "films_tenantId_releaseDate_idx" ON "films"("tenantId", "releaseDate");

-- CreateIndex
CREATE INDEX "films_tenantId_isFeatured_idx" ON "films"("tenantId", "isFeatured");

-- CreateIndex
CREATE UNIQUE INDEX "films_tenantId_slug_key" ON "films"("tenantId", "slug");

-- CreateIndex
CREATE UNIQUE INDEX "film_pricing_filmId_key" ON "film_pricing"("filmId");

-- CreateIndex
CREATE UNIQUE INDEX "film_availability_filmId_key" ON "film_availability"("filmId");

-- CreateIndex
CREATE INDEX "film_assets_filmId_type_idx" ON "film_assets"("filmId", "type");

-- CreateIndex
CREATE INDEX "film_assets_filmId_isPrimary_idx" ON "film_assets"("filmId", "isPrimary");

-- CreateIndex
CREATE INDEX "film_subtitles_filmId_idx" ON "film_subtitles"("filmId");

-- CreateIndex
CREATE UNIQUE INDEX "film_subtitles_filmId_languageCode_kind_key" ON "film_subtitles"("filmId", "languageCode", "kind");

-- CreateIndex
CREATE INDEX "film_chapters_filmId_orderIndex_idx" ON "film_chapters"("filmId", "orderIndex");

-- CreateIndex
CREATE INDEX "film_variants_filmId_qualityLabel_idx" ON "film_variants"("filmId", "qualityLabel");

-- CreateIndex
CREATE INDEX "film_variants_filmId_isDefault_idx" ON "film_variants"("filmId", "isDefault");

-- CreateIndex
CREATE INDEX "genres_tenantId_isActive_idx" ON "genres"("tenantId", "isActive");

-- CreateIndex
CREATE UNIQUE INDEX "genres_tenantId_slug_key" ON "genres"("tenantId", "slug");

-- CreateIndex
CREATE INDEX "film_genres_genreId_idx" ON "film_genres"("genreId");

-- CreateIndex
CREATE INDEX "bundles_tenantId_status_idx" ON "bundles"("tenantId", "status");

-- CreateIndex
CREATE UNIQUE INDEX "bundles_tenantId_slug_key" ON "bundles"("tenantId", "slug");

-- CreateIndex
CREATE INDEX "film_bundle_items_filmId_idx" ON "film_bundle_items"("filmId");

-- CreateIndex
CREATE UNIQUE INDEX "film_bundle_items_bundleId_filmId_key" ON "film_bundle_items"("bundleId", "filmId");

-- CreateIndex
CREATE INDEX "watchlist_items_tenantId_viewerUserId_idx" ON "watchlist_items"("tenantId", "viewerUserId");

-- CreateIndex
CREATE INDEX "watchlist_items_filmId_idx" ON "watchlist_items"("filmId");

-- CreateIndex
CREATE UNIQUE INDEX "watchlist_items_tenantId_viewerUserId_filmId_key" ON "watchlist_items"("tenantId", "viewerUserId", "filmId");

-- CreateIndex
CREATE INDEX "film_ratings_filmId_isPublished_idx" ON "film_ratings"("filmId", "isPublished");

-- CreateIndex
CREATE UNIQUE INDEX "film_ratings_tenantId_viewerUserId_filmId_key" ON "film_ratings"("tenantId", "viewerUserId", "filmId");

-- AddForeignKey
ALTER TABLE "films" ADD CONSTRAINT "films_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "film_pricing" ADD CONSTRAINT "film_pricing_filmId_fkey" FOREIGN KEY ("filmId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "film_availability" ADD CONSTRAINT "film_availability_filmId_fkey" FOREIGN KEY ("filmId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "film_assets" ADD CONSTRAINT "film_assets_filmId_fkey" FOREIGN KEY ("filmId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "film_subtitles" ADD CONSTRAINT "film_subtitles_filmId_fkey" FOREIGN KEY ("filmId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "film_chapters" ADD CONSTRAINT "film_chapters_filmId_fkey" FOREIGN KEY ("filmId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "film_variants" ADD CONSTRAINT "film_variants_filmId_fkey" FOREIGN KEY ("filmId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "film_genres" ADD CONSTRAINT "film_genres_filmId_fkey" FOREIGN KEY ("filmId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "film_genres" ADD CONSTRAINT "film_genres_genreId_fkey" FOREIGN KEY ("genreId") REFERENCES "genres"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "film_bundle_items" ADD CONSTRAINT "film_bundle_items_bundleId_fkey" FOREIGN KEY ("bundleId") REFERENCES "bundles"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "film_bundle_items" ADD CONSTRAINT "film_bundle_items_filmId_fkey" FOREIGN KEY ("filmId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "watchlist_items" ADD CONSTRAINT "watchlist_items_filmId_fkey" FOREIGN KEY ("filmId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "film_ratings" ADD CONSTRAINT "film_ratings_filmId_fkey" FOREIGN KEY ("filmId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE;
